### ISSUE TITLE
Aviator crashes during conversion of a mp4 video

### ISSUE THREAD

**Issue by BuZZ-dEE** [gianni-rosato/aviator#39] opened 2023-06-04 15:05 UTC
Aviator crashes during conversion of a mp4 video. If I change the target resolution to 1080x1920 the conversion is completed successfully. 

Source video properties:

![grafik](https://github.com/gianni-rosato/aviator/assets/125954/21ee1aff-1423-4185-8cb3-577306239f3c)

I replaced the complete path by `~/` in the following command.
```
flatpak run net.natesales.Aviator
['ffmpeg', '-nostdin', '-y', '-i', '~/VID_20230604_095032.mp4', '-y', '-y', '-map', '0:v', '-c:v', 'libsvtav1', '-crf', '32', '-preset', '6', '-pix_fmt', 'yuv420p10le', '-svtav1-params', 'film-grain=0:input-depth=10:tune=2:keyint=10s:film-grain-denoise=0', '-map', '0:a?', '-c:a', 'libopus', '-b:a', '48K', '-y', '-y', '-ac', '0', '-map', '-0:s', '-c:s', 'copy', '-metadata', 'comment="Encoded with Aviator"', '~/VID_20230604_095032.webm']
0/100
12/100
12/100
12/100
24/100
37/100
37/100
37/100
49/100
49/100
49/100
49/100
49/100
49/100
49/100
49/100
61/100
61/100
61/100
61/100
61/100
61/100
61/100
61/100
61/100
61/100
61/100
61/100
fish: Job 1, 'flatpak run net.natesales.Aviat…' terminated by signal SIGTERM (Höfliche Beendigungsanforderung)
```

**Comment by gianni-rosato** [comment] 2023-06-04 15:12
Would you mind sharing the source video?

**Comment by BuZZ-dEE** [comment] 2023-06-04 15:32
https://cloud.disroot.org/s/i78FzdwjNF9pZ3S

**Comment by BuZZ-dEE** [comment] 2023-06-05 11:15
@gianni-rosato can you locate problem?

**Comment by gianni-rosato** [comment] 2023-06-06 01:31
I was able to test today. The encode was successful leaving all of the settings at their defaults. Here's the resulting video: 
[aviator_bug_test1.zip](https://github.com/gianni-rosato/aviator/files/11658966/aviator_bug_test1.zip)

My FFmpeg output, ignore the GTK error (I cannot fix that, that is on GNOME's side):

```flatpak run net.natesales.Aviator 
['ffmpeg', '-nostdin', '-y', '-i', '/home/gianni13700k/Downloads/VID_20230604_095032.mp4', '-y', '-y', '-map', '0:v', '-c:v', 'libsvtav1', '-crf', '32', '-preset', '6', '-pix_fmt', 'yuv420p10le', '-svtav1-params', 'film-grain=0:input-depth=10:tune=2:keyint=10s:film-grain-denoise=0', '-map', '0:a?', '-c:a', 'libopus', '-b:a', '48K', '-y', '-y', '-ac', '0', '-map', '0:s?', '-c:s', 'copy', '-metadata', 'comment="Encoded with Aviator"', '/home/gianni13700k/Downloads/aviator_bug_1.mkv']
0/100
12/100
12/100
37/100
49/100
74/100
86/100
86/100
86/100
86/100
86/100
86/100
86/100
86/100
98/100
98/100
98/100
98/100
98/100
99/100
99/100
99/100
99/100
99/100
99/100

(aviator:2): Gtk-WARNING **: 21:28:18.955: Trying to snapshot GtkGizmo 0x55b0c0eb0eb0 without a current allocation
99/100
100/100```

Would you mind sending me the output of `inxi -v`? Thanks.

**Comment by gianni-rosato** [comment] 2023-06-06 01:32
Would you mind sending me the output of `inxi -v`? Thanks.

**Comment by BuZZ-dEE** [comment] 2023-06-07 08:29
@gianni-rosato output of `inxi -v`:

```
12CPU quad core Intel Core i7-6700T (-MT MCP-) 12speed/min/max 900/800/3600 MHz
12Kernel 6.3.5-zen2-1-zen x86_64 12Up 1d 57m 12Mem 4759.1/15911.1 MiB (29.9%)
12Storage 1.38 TiB (16.8% used) 12Procs 309 12Client Unknown Client: flatpak-session-helper 12inxi 3.3.27
```

**Comment by BuZZ-dEE** [comment] 2023-06-07 13:19
> Try playing it in Celluloid, MPV, or VLC. It works for me just fine, and not every player has perfect AV1 support.

But this video [VID_20230604_095032.zip](https://github.com/gianni-rosato/aviator/files/11677438/VID_20230604_095032.zip) plays fine.

> In the meantime, I think you're running out of RAM trying to encode that 4k video. I'll consider adding a warning to the Export page that AV1 encoding is not a lightweight process, but in the meantime there's nothing I can do about your issue to solve it directly. I have 32gb of RAM and it worked flawlessly for me, but it did use >50% of my memory.

Why should it not be possible to convert such a video with 16GB RAM? The source video is only 47MB big and 8 seconds long.

**Comment by gianni-rosato** [comment] 2023-06-07 13:23
Please try the video in the enclosed ZIP in one of the supported players.

The problem is the video is 4k, and encoding doesn't use less RAM instantaneously based on the filesize or length of a video. I'm going to close this issue.

**Comment by BuZZ-dEE** [comment] 2023-06-14 14:51
@gianni-rosato I think you should leave this open until you find a solution to this problem. Whatever the solution is.

**Comment by gianni-rosato** [comment] 2023-06-14 14:52
The solution is your system isn't capable of encoding AV1 video at 4k, as it is very resource intensive. You can get more RAM to potentially solve it. This is not my problem.

**Comment by BuZZ-dEE** [comment] 2023-06-14 15:01
A crashing app, that you develop, is not your problem? Ok.

**Comment by trixoniisama** [comment] 2023-06-14 15:43
You are doing strange things with the resolution... This is not a fair comparison.

**Comment by BuZZ-dEE** [comment] 2023-06-14 15:48
> You are doing strange things with the resolution...

What is strange?

> This is not a fair comparison.

The user has the goal to minimize a video and you see it is possible.

**Comment by BuZZ-dEE** [comment] 2023-06-14 20:19
> > You are doing strange things with the resolution...
> 
> What is strange?
> 
> > This is not a fair comparison.


Ah, I found want you meant. The target resolution was 2160x2160. Ok, that was really not a fair comparison, but I corrected the target resolution to 2160x3840 and it still works. I also updated the images and the resulting video in the [above post](https://github.com/gianni-rosato/aviator/issues/39#issuecomment-1591473607).

**Comment by gianni-rosato** [comment] 2023-06-14 20:42
Would you please test the following script to test if it works on your video? Run in the path & replace `[source]` with your video's filename.

`ffmpeg -i [source] -c:v libsvtav1 -preset 6 -crf 6 -pix_fmt yuv420p10le -svtav1-params input-depth=10:tune=1:keyint=10s -c:a libopus -b:a 128K -map -0:s output.mkv`

Let me know if this works.

**Comment by BuZZ-dEE** [comment] 2023-06-15 20:40
@gianni-rosato 

```
# ffmpeg -i VID_20230604_095032.mp4 -c:v libsvtav1 -preset 6 -crf 32 -pix_fmt yuv420p10le -svtav1-params input-depth=10:tune=1:keyint=10s -c:a libopus -b:a 128K -map -0:s output.mkv
ffmpeg version n6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.1.1 (GCC) 20230429
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'VID_20230604_095032.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2023-06-04T07:50:42.000000Z
    com.android.version: 12
    com.android.capture.fps: 30.000000
  Duration: 00:00:08.94, start: 0.000000, bitrate: 42092 kb/s
  Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt470bg/bt470bg/smpte170m, progressive), 3840x2160, 41758 kb/s, 29.66 fps, 30 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2023-06-04T07:50:42.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
    Side data:
      displaymatrix: rotation of -90.00 degrees
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 156 kb/s (default)
    Metadata:
      creation_time   : 2023-06-04T07:50:42.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
Stream map '0:s' matches no streams.
To ignore this, add a trailing '?' to the map.
```

**Comment by gianni-rosato** [comment] 2023-06-15 20:42
Ah, my apologies, your video doesn't contain subtitles. Here, try this again:

`ffmpeg -i [source] -c:v libsvtav1 -preset 6 -crf 32 -pix_fmt yuv420p10le -svtav1-params input-depth=10:tune=1:keyint=10s -c:a libopus -b:a 128K output.mkv`

**Comment by BuZZ-dEE** [comment] 2023-06-16 12:59
@gianni-rosato 

```
# ffmpeg -i VID_20230604_095032.mp4 -c:v libsvtav1 -preset 6 -crf 32 -pix_fmt yuv420p10le -svtav1-params input-depth=10:tune=1:keyint=10s -c:a libopus -b:a 128K output.mkv
ffmpeg version n6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.1.1 (GCC) 20230429
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'VID_20230604_095032.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2023-06-04T07:50:42.000000Z
    com.android.version: 12
    com.android.capture.fps: 30.000000
  Duration: 00:00:08.94, start: 0.000000, bitrate: 42092 kb/s
  Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt470bg/bt470bg/smpte170m, progressive), 3840x2160, 41758 kb/s, 29.66 fps, 30 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2023-06-04T07:50:42.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
    Side data:
      displaymatrix: rotation of -90.00 degrees
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 156 kb/s (default)
    Metadata:
      creation_time   : 2023-06-04T07:50:42.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> av1 (libsvtav1))
  Stream #0:1 -> #0:1 (aac (native) -> opus (libopus))
Press [q] to stop, [?] for help
[swscaler @ 0x556fa76a35c0] deprecated pixel format used, make sure you did set range correctly
    Last message repeated 1 times
[swscaler @ 0x556fa76b1280] deprecated pixel format used, make sure you did set range correctly
Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v1.5.0-dirty
Svt[info]: SVT [build]  :	GCC 12.2.1 20230201	 64 bit
Svt[info]: LIB Build date: Apr 27 2023 15:18:53
Svt[info]: -------------------------------------------
Svt[info]: Number of logical cores available: 8
Svt[info]: Number of PPCS 106
Svt[info]: [asm level on system : up to avx2]
Svt[info]: [asm level selected : up to avx2]
Svt[info]: -------------------------------------------
Svt[info]: SVT [config]: main profile	tier (auto)	level (auto)
Svt[info]: SVT [config]: width / height / fps numerator / fps denominator 		: 2160 / 3840 / 30 / 1
Svt[info]: SVT [config]: bit-depth / color format 					: 10 / YUV420
Svt[info]: SVT [config]: preset / tune / pred struct 					: 6 / PSNR / random access
Svt[info]: SVT [config]: gop size / mini-gop size / key-frame type 			: 301 / 32 / key frame
Svt[info]: SVT [config]: BRC mode / rate factor 					: CRF / 32 
Svt[info]: -------------------------------------------
SvtMalloc[info]: SVT Memory Usage:
SvtMalloc[info]:     total allocated memory:       15.44 GB
SvtMalloc[info]:         malloced memory:          2.93 GB
SvtMalloc[info]:         callocated memory:        119.07 MB
SvtMalloc[info]:         allocated aligned memory: 12.39 GB
SvtMalloc[info]:     mutex count: 26240
SvtMalloc[info]:     semaphore count: 2781
SvtMalloc[info]:     thread count: 673
SvtMalloc[info]:     hash table fulless: 0.285992, hash bucket is healthy
SvtMalloc[info]: top 10 malloced memory locations:
SvtMalloc[info]: (1.34 GB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbCodingUnit.c:78
SvtMalloc[info]: (327.43 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:123
SvtMalloc[info]: (318.75 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:1192
SvtMalloc[info]: (220.25 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:1581
SvtMalloc[info]: (212.83 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:124
SvtMalloc[info]: (122.36 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:1585
SvtMalloc[info]: (91.58 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Common/Codec/EbBitstreamUnit.c:37
SvtMalloc[info]: (63.75 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:1169
SvtMalloc[info]: (39.84 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:1165
SvtMalloc[info]: (26.56 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbModeDecisionProcess.c:179
    Last message repeated 1 times
Output #0, matroska, to 'output.mkv':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    com.android.capture.fps: 30.000000
    com.android.version: 12
    encoder         : Lavf60.3.100
  Stream #0:0(eng): Video: av1 (AV01 / 0x31305641), yuv420p10le(tv, bt470bg/bt470bg/smpte170m, progressive), 2160x3840, q=2-31, 30 fps, 1k tbn (default)
    Metadata:
      creation_time   : 2023-06-04T07:50:42.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.3.100 libsvtav1
    Side data:
      displaymatrix: rotation of -0.00 degrees
  Stream #0:1(eng): Audio: opus ([255][255][255][255] / 0xFFFFFFFF), 48000 Hz, stereo, flt, 128 kb/s (default)
    Metadata:
      creation_time   : 2023-06-04T07:50:42.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.3.100 libopus
fish: Job 1, 'ffmpeg -i VID_20230604_095032.m…' terminated by signal SIGKILL (Erzwungene Beendigung)
```

[output.zip](https://github.com/gianni-rosato/aviator/files/11770485/output.zip)

**Comment by gianni-rosato** [comment] 2023-06-16 13:11
`Job 1, 'ffmpeg -i VID_20230604_095032.m…' terminated by signal SIGKILL` Did the job actually finish without issue & the video plays back fine?

If so, I'll have to test further. This may be an issue stemming from Aviator's custom SVT-AV1 fork, in which case I'll talk to the fork's maintainer. Since I have your source video, I'll continue to try and reproduce your issue. I appreciate your patience.

**Comment by gianni-rosato** [comment] 2023-06-16 16:45
Ah okay, gotcha. I'm unable to reproduce this issue, as everything works fine for me, and if you're experiencing this problem with FFmpeg it is worth bringing it up to their devs instead and asking around there.

I still thing this is a hardware limitation, but considering you have the _same_ problem with Aviator _entirely_ out of the equation, I will be closing this issue. Thanks for your patience.

**Closed** 2023-06-16 16:45 UTC
